# Generated by Django 3.2 on 2023-03-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20230305_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(help_text='角色, 醫師, 診所, 技工所', max_length=100, null=True),
        ),
    ]
