# Generated by Django 3.2 on 2023-04-10 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_user_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='top_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_created_users', to=settings.AUTH_USER_MODEL, verbose_name='上級創建者'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='創建者'),
        ),
    ]
