# Generated by Django 3.2 on 2023-04-16 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_order_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='clinc_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinc_created_by', to=settings.AUTH_USER_MODEL, verbose_name='創建者'),
        ),
    ]
