# Generated by Django 3.2 on 2023-04-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_order_clinc_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='clinics',
            field=models.ManyToManyField(blank=True, to='system.Clinic', verbose_name='診所連接'),
        ),
        migrations.AlterField(
            model_name='order',
            name='patient',
            field=models.CharField(max_length=32, null=True, verbose_name='病患名稱'),
        ),
        migrations.AlterField(
            model_name='order',
            name='patients',
            field=models.ManyToManyField(blank=True, to='system.Patient', verbose_name='病患連接'),
        ),
    ]
