# Generated by Django 3.2 on 2023-04-16 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20230416_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='clinics',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='診所連接'),
        ),
    ]
