# Generated by Django 3.2 on 2023-04-24 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_alter_order_clinics'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='by_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patient', to=settings.AUTH_USER_MODEL, verbose_name='創建者'),
        ),
        migrations.AddField(
            model_name='patient',
            name='clinc_by_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_clinc_by_created', to=settings.AUTH_USER_MODEL, verbose_name='上級創建者'),
        ),
    ]
