# Generated by Django 3.2 on 2023-05-14 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_alter_patient_clinc_by_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturers',
            name='parentId',
        ),
        migrations.AddField(
            model_name='manufacturers',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.manufacturers', verbose_name='父'),
        ),
    ]
