# Generated by Django 3.2 on 2023-05-14 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_auto_20230514_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturers',
            name='long',
        ),
    ]
