# Generated by Django 3.2.6 on 2023-06-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_auto_20230514_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldict',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical 字典'},
        ),
        migrations.AlterField(
            model_name='historicaldict',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
