# Generated by Django 3.2.6 on 2023-07-19 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_auto_20230624_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='equipment_rental',
            new_name='Equipment_rental',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='surgical_method',
            new_name='Surgical_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Implant_brand',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Implant_size',
        ),
        migrations.RemoveField(
            model_name='order',
            name='action_required',
        ),
        migrations.RemoveField(
            model_name='order',
            name='avatar_3d_jaw_Bite',
        ),
        migrations.RemoveField(
            model_name='order',
            name='avatar_3d_jaw_RayTray',
        ),
        migrations.RemoveField(
            model_name='order',
            name='avatar_3d_jaw_Scanbody',
        ),
        migrations.RemoveField(
            model_name='order',
            name='avatar_3d_palate_Bite',
        ),
        migrations.RemoveField(
            model_name='order',
            name='avatar_3d_palate_RayTray',
        ),
        migrations.RemoveField(
            model_name='order',
            name='avatar_3d_palate_Scanbody',
        ),
        migrations.RemoveField(
            model_name='order',
            name='metal_scattering',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='order',
            name='surgery_date',
        ),
        migrations.AddField(
            model_name='order',
            name='CBCT_order_method',
            field=models.CharField(max_length=32, null=True, verbose_name='CBCT入單方式'),
        ),
        migrations.AddField(
            model_name='order',
            name='Dental_implant_type',
            field=models.CharField(max_length=32, null=True, verbose_name='手術植牙類型'),
        ),
        migrations.AddField(
            model_name='order',
            name='Implant_Surgical_Board',
            field=models.CharField(max_length=32, null=True, verbose_name='產品項目_植牙手術版'),
        ),
        migrations.AddField(
            model_name='order',
            name='Implant_Surgical_Board_temporary_tooth',
            field=models.CharField(max_length=32, null=True, verbose_name='產品項目_植牙手術版+臨時牙冠'),
        ),
        migrations.AddField(
            model_name='order',
            name='Jaw_surgery_date',
            field=models.CharField(max_length=32, null=True, verbose_name='植牙手術板下顎手術日期'),
        ),
        migrations.AddField(
            model_name='order',
            name='Jaw_weardate',
            field=models.CharField(max_length=32, null=True, verbose_name='植牙手術板下顎裝戴日期'),
        ),
        migrations.AddField(
            model_name='order',
            name='Order_Type',
            field=models.CharField(max_length=32, null=True, verbose_name='訂單類型'),
        ),
        migrations.AddField(
            model_name='order',
            name='Palate_surgery_date',
            field=models.CharField(max_length=32, null=True, verbose_name='植牙手術板上顎手術日期'),
        ),
        migrations.AddField(
            model_name='order',
            name='Palate_weardate',
            field=models.CharField(max_length=32, null=True, verbose_name='植牙手術板上顎裝戴日期'),
        ),
        migrations.AddField(
            model_name='order',
            name='Payment_method',
            field=models.CharField(max_length=32, null=True, verbose_name='付款方式'),
        ),
        migrations.AddField(
            model_name='order',
            name='Positioning_plate',
            field=models.CharField(max_length=32, null=True, verbose_name='產品項目_定位板'),
        ),
        migrations.AddField(
            model_name='order',
            name='Positioning_plate_Metal_scattering',
            field=models.CharField(max_length=32, null=True, verbose_name='定位板金屬散射'),
        ),
        migrations.AddField(
            model_name='order',
            name='Positioning_plate_Natural_teeth',
            field=models.CharField(max_length=32, null=True, verbose_name='定位板自然牙'),
        ),
        migrations.AddField(
            model_name='order',
            name='Positioning_plate_STL_order_method',
            field=models.CharField(max_length=32, null=True, verbose_name='定位板STL入單方式'),
        ),
        migrations.AddField(
            model_name='order',
            name='Positioning_plate_jaw_date',
            field=models.CharField(max_length=32, null=True, verbose_name='定位板下顎裝戴日期'),
        ),
        migrations.AddField(
            model_name='order',
            name='Positioning_plate_palate_date',
            field=models.CharField(max_length=32, null=True, verbose_name='定位板上顎裝戴日期'),
        ),
        migrations.AddField(
            model_name='order',
            name='Positioning_plate_remark',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='定位板備註'),
        ),
        migrations.AddField(
            model_name='order',
            name='Surgical_board_Metal_scattering',
            field=models.CharField(max_length=32, null=True, verbose_name='手術板金屬散射'),
        ),
        migrations.AddField(
            model_name='order',
            name='Surgical_board_Natural_teeth',
            field=models.CharField(max_length=32, null=True, verbose_name='手術板自然牙'),
        ),
        migrations.AddField(
            model_name='order',
            name='Surgical_board_STL_order_method',
            field=models.CharField(max_length=32, null=True, verbose_name='手術板STL入單方式'),
        ),
        migrations.AddField(
            model_name='order',
            name='Surgical_board_remark',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='手術板備註'),
        ),
        migrations.AddField(
            model_name='order',
            name='T11_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T11植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T11_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T11植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T12_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T12植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T12_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T12植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T13_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T13植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T13_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T13植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T14_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T14植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T14_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T14植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T15_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T15植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T15_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T15植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T16_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T16植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T16_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T16植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T17_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T17植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T17_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T17植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T18_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T18植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T18_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T18植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T21_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T21植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T21_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T21植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T22_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T22植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T22_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T22植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T23_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T23植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T23_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T23植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T24_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T24植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T24_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T24植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T25_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T25植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T25_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T25植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T26_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T26植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T26_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T26植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T27_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T27植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T27_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T27植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T28_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T28植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T28_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T28植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T31_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T31植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T31_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T31植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T32_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T32植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T32_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T32植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T33_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T33植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T33_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T33植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T34_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T34植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T34_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T34植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T35_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T35植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T35_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T35植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T36_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T36植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T36_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T36植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T37_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T37植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T37_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T37植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T38_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T38植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T38_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T38植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T41_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T41植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T41_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T41植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T42_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T42植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T42_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T42植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T43_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T43植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T43_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T43植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T44_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T44植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T44_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T44植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T45_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T45植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T45_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T45植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T46_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T46植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T46_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T46植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T47_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T47植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T47_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T47植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='T48_Implant_brand',
            field=models.TextField(max_length=32, null=True, verbose_name='T48植體廠牌'),
        ),
        migrations.AddField(
            model_name='order',
            name='T48_Implant_size',
            field=models.TextField(max_length=32, null=True, verbose_name='T48植體廠牌尺寸'),
        ),
        migrations.AddField(
            model_name='order',
            name='Temporary_tooth',
            field=models.CharField(max_length=32, null=True, verbose_name='臨牙'),
        ),
        migrations.AddField(
            model_name='order',
            name='Top_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Top_created_by', to=settings.AUTH_USER_MODEL, verbose_name='技工所創建者'),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=32, null=True, verbose_name='收件地址'),
        ),
        migrations.AddField(
            model_name='order',
            name='draft_status',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='草稿狀態'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=32, null=True, verbose_name='電話號碼'),
        ),
        migrations.AlterField(
            model_name='manufacturers',
            name='name',
            field=models.CharField(max_length=32, verbose_name='名稱'),
        ),
        migrations.AlterField(
            model_name='order',
            name='avatar_3d_jaw',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='3D下顎模型'),
        ),
        migrations.AlterField(
            model_name='order',
            name='avatar_3d_jaw_Denture',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='3D下顎模型Denture'),
        ),
        migrations.AlterField(
            model_name='order',
            name='avatar_3d_palate',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='3D上顎模型'),
        ),
        migrations.AlterField(
            model_name='order',
            name='avatar_3d_palate_Denture',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='3D上顎模型Denture'),
        ),
        migrations.AlterField(
            model_name='order',
            name='avatar_CT',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='CT'),
        ),
        migrations.AlterField(
            model_name='order',
            name='avatar_image1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='病患照片1'),
        ),
        migrations.AlterField(
            model_name='order',
            name='avatar_image2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='病患照片2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='avatar_image3',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='病患照片3'),
        ),
        migrations.AlterField(
            model_name='order',
            name='avatar_image4',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='病患照片4'),
        ),
        migrations.AlterField(
            model_name='order',
            name='avatar_image5',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='病患照片5'),
        ),
        migrations.AlterField(
            model_name='order',
            name='avatar_image6',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='病患照片6'),
        ),
        migrations.AlterField(
            model_name='order',
            name='avatar_image7',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='病患照片7'),
        ),
        migrations.AlterField(
            model_name='order',
            name='avatar_image8',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='病患照片8'),
        ),
        migrations.AlterField(
            model_name='order',
            name='avatar_image9',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='病患照片9'),
        ),
        migrations.AlterField(
            model_name='order',
            name='avatar_project',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='專案'),
        ),
        migrations.AlterField(
            model_name='order',
            name='clinc_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinc_created_by', to=settings.AUTH_USER_MODEL, verbose_name='診所創建者'),
        ),
        migrations.AlterField(
            model_name='order',
            name='design',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='設計師設計檔'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=32, null=True, verbose_name='訂單號'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手機號碼'),
        ),
    ]
