# Generated by Django 3.2.6 on 2023-08-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_auto_20230719_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldict',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical 字典', 'verbose_name_plural': 'historical 字典'},
        ),
        migrations.AlterField(
            model_name='historicaldict',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
