# Generated by Django 3.2.6 on 2023-09-13 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_auto_20230816_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='docter',
            new_name='doctor',
        ),
        migrations.AddField(
            model_name='order',
            name='doctors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.doctor', verbose_name='醫師連接'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='patients',
        ),
        migrations.AddField(
            model_name='order',
            name='patients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.patient', verbose_name='病患連接'),
        ),
    ]
