# Generated by Django 3.2.6 on 2023-09-13 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_auto_20230913_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='clinics',
        ),
        migrations.AlterField(
            model_name='order',
            name='doctors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='醫師連接'),
        ),
    ]
