# Generated by Django 3.2.6 on 2023-09-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_auto_20230913_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='T11_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T11植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T11_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T11植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T12_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T12植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T12_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T12植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T13_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T13植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T13_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T13植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T14_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T14植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T14_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T14植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T15_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T15植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T15_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T15植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T16_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T16植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T16_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T16植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T17_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T17植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T17_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T17植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T18_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T18植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T18_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T18植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T21_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T21植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T21_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T21植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T22_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T22植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T22_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T22植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T23_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T23植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T23_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T23植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T24_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T24植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T24_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T24植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T25_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T25植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T25_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T25植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T26_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T26植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T26_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T26植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T27_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T27植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T27_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T27植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T28_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T28植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T28_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T28植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T31_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T31植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T31_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T31植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T32_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T32植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T32_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T32植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T33_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T33植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T33_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T33植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T34_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T34植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T34_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T34植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T35_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T35植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T35_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T35植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T36_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T36植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T36_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T36植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T37_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T37植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T37_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T37植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T38_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T38植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T38_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T38植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T41_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T41植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T41_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T41植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T42_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T42植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T42_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T42植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T43_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T43植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T43_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T43植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T44_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T44植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T44_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T44植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T45_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T45植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T45_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T45植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T46_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T46植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T46_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T46植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T47_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T47植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T47_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T47植體廠牌尺寸'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T48_Implant_brand',
            field=models.TextField(max_length=256, null=True, verbose_name='T48植體廠牌'),
        ),
        migrations.AlterField(
            model_name='order',
            name='T48_Implant_size',
            field=models.TextField(max_length=256, null=True, verbose_name='T48植體廠牌尺寸'),
        ),
    ]
