# Generated by Django 3.2.6 on 2022-08-21 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='創建時間', verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改時間', verbose_name='修改時間')),
                ('is_deleted', models.BooleanField(default=False, help_text='刪除標記', verbose_name='刪除標記')),
                ('name', models.CharField(max_length=50, verbose_name='名稱')),
                ('is_hidden', models.BooleanField(default=False, help_text='設置為True時,獲取工單步驟api中不顯示此狀態(當前處於此狀態時除外)', verbose_name='是否隱藏')),
                ('sort', models.IntegerField(default=0, help_text='用於工單步驟介面時，step上狀態的順序(因為存在網狀情況，所以需要人為設定順序),值越小越靠前', verbose_name='狀態順序')),
                ('type', models.IntegerField(choices=[(0, '普通'), (1, '開始'), (2, '結束')], default=0, help_text='0.普通類型 1.初始狀態(用於新建工單時,獲取對應的欄位必填及transition信息) 2.結束狀態(此狀態下的工單不得再處理，即沒有對應的transition)', verbose_name='狀態類型')),
                ('enable_retreat', models.BooleanField(default=False, help_text='開啟後允許工單創建人在此狀態直接撤回工單到初始狀態', verbose_name='允許撤回')),
                ('participant_type', models.IntegerField(blank=True, choices=[(0, '無處理人'), (1, '個人'), (2, '多人'), (4, '角色'), (6, '腳本'), (7, '工單的欄位'), (9, '代碼獲取')], default=1, help_text='0.無處理人,1.個人,2.多人,3.部門,4.角色,5.變量(支持工單創建人,創建人的leader),6.腳本,7.工單的欄位內容(如表單中的"測試負責人"，需要為用戶名或者逗號隔開的多個用戶名),8.父工單的欄位內容。 初始狀態請選擇類型5，參與人填create_by', verbose_name='參與者類型')),
                ('participant', models.JSONField(blank=True, default=list, help_text='可以為空(無處理人的情況，如結束狀態)、userid、userid列表\\部門id\\角色id\\變量(create_by,create_by_tl)\\腳本記錄的id等，包含子工作流的需要設置處理人為loonrobot', verbose_name='參與者')),
                ('state_fields', models.JSONField(default=dict, help_text='json格式字典存儲,包括讀寫屬性1：只讀，2：必填，3：可選, 4:隱藏 示例：{"create_time":1,"title":2, "sn":1}, 內置特殊欄位participant_info.participant_name:當前處理人信息(部門名稱、角色名稱)，state.state_name:當前狀態的狀態名,workflow.workflow_name:工作流名稱', verbose_name='表單欄位')),
                ('distribute_type', models.IntegerField(choices=[(1, '主動接單'), (2, '直接處理'), (3, '隨機分配'), (4, '全部處理')], default=1, help_text='1.主動接單(如果當前處理人實際為多人的時候，需要先接單才能處理) 2.直接處理(即使當前處理人實際為多人，也可以直接處理) 3.隨機分配(如果實際為多人，則系統會隨機分配給其中一個人) 4.全部處理(要求所有參與人都要處理一遍,才能進入下一步)', verbose_name='分配方式')),
                ('filter_policy', models.IntegerField(choices=[(0, '無'), (1, '和工單同屬一及上級部門'), (2, '和創建人同屬一及上級部門'), (3, '和上步處理人同屬一及上級部門')], default=0, verbose_name='參與人過濾策略')),
                ('participant_cc', models.JSONField(blank=True, default=list, help_text='抄送給(userid列表)', verbose_name='抄送給')),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_create_by', to=settings.AUTH_USER_MODEL, verbose_name='創建人')),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_update_by', to=settings.AUTH_USER_MODEL, verbose_name='最後編輯人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='創建時間', verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改時間', verbose_name='修改時間')),
                ('is_deleted', models.BooleanField(default=False, help_text='刪除標記', verbose_name='刪除標記')),
                ('title', models.CharField(blank=True, help_text='工單標題', max_length=500, null=True, verbose_name='標題')),
                ('sn', models.CharField(help_text='工單的流水號', max_length=25, verbose_name='流水號')),
                ('ticket_data', models.JSONField(default=dict, help_text='工單自定義欄位內容', verbose_name='工單數據')),
                ('in_add_node', models.BooleanField(default=False, help_text='是否處於加簽狀態下', verbose_name='加簽狀態中')),
                ('script_run_last_result', models.BooleanField(default=True, verbose_name='腳本最後一次執行結果')),
                ('participant_type', models.IntegerField(choices=[(0, '無處理人'), (1, '個人'), (2, '多人'), (4, '角色'), (6, '腳本'), (7, '工單的欄位'), (9, '代碼獲取')], default=0, help_text='0.無處理人,1.個人,2.多人', verbose_name='當前處理人類型')),
                ('participant', models.JSONField(blank=True, default=list, help_text='可以為空(無處理人的情況，如結束狀態)、userid、userid列表', verbose_name='當前處理人')),
                ('act_state', models.IntegerField(choices=[(0, '草稿中'), (1, '進行中'), (2, '被退回'), (3, '被撤回'), (4, '已完成'), (5, '已關閉')], default=1, help_text='當前工單的進行狀態', verbose_name='進行狀態')),
                ('multi_all_person', models.JSONField(blank=True, default=dict, help_text='需要當前狀態處理人全部處理時實際的處理結果，json格式', verbose_name='全部處理的結果')),
                ('add_node_man', models.ForeignKey(blank=True, help_text='加簽操作的人，工單當前處理人處理完成後會回到該處理人，當處於加簽狀態下才有效', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='加簽人')),
                ('belong_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_belong_dept', to='system.organization', verbose_name='所屬部門')),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_create_by', to=settings.AUTH_USER_MODEL, verbose_name='創建人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wf.ticket', verbose_name='父工單')),
                ('parent_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_parent_state', to='wf.state', verbose_name='父工單狀態')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_state', to='wf.state', verbose_name='當前狀態')),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_update_by', to=settings.AUTH_USER_MODEL, verbose_name='最後編輯人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='創建時間', verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改時間', verbose_name='修改時間')),
                ('is_deleted', models.BooleanField(default=False, help_text='刪除標記', verbose_name='刪除標記')),
                ('name', models.CharField(max_length=50, verbose_name='名稱')),
                ('key', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='工作流標識')),
                ('sn_prefix', models.CharField(default='hb', max_length=50, verbose_name='流水號前綴')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('view_permission_check', models.BooleanField(default=True, help_text='開啟後，只允許工單的關聯人(創建人、曾經的處理人)有權限查看工單', verbose_name='查看權限校驗')),
                ('limit_expression', models.JSONField(blank=True, default=dict, help_text='限制周期({"period":24} 24小時), 限制次數({"count":1}在限制周期內只允許提交1次), 限制級別({"level":1} 針對(1單個用戶 2全局)限制周期限制次數,默認特定用戶);允許特定人員提交({"allow_persons":"zhangsan,lisi"}只允許張三提交工單,{"allow_depts":"1,2"}只允許部門id為1和2的用戶提交工單，{"allow_roles":"1,2"}只允許角色id為1和2的用戶提交工單)', verbose_name='限製表達式')),
                ('display_form_str', models.JSONField(blank=True, default=list, help_text='默認"[]"，用於用戶只有對應工單查看權限時顯示哪些欄位,field_key的list的json,如["days","sn"],內置特殊欄位participant_info.participant_name:當前處理人信息(部門名稱、角色名稱)，state.state_name:當前狀態的狀態名,workflow.workflow_name:工作流名稱', verbose_name='展現表單欄位')),
                ('title_template', models.CharField(blank=True, default='{title}', help_text='工單欄位的值可以作為參數寫到模板中，格式如：你有一個待辦工單:{title}', max_length=50, null=True, verbose_name='標題模板')),
                ('content_template', models.CharField(blank=True, default='標題:{title}, 創建時間:{create_time}', help_text='工單欄位的值可以作為參數寫到模板中，格式如：標題:{title}, 創建時間:{create_time}', max_length=1000, null=True, verbose_name='內容模板')),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_create_by', to=settings.AUTH_USER_MODEL, verbose_name='創建人')),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_update_by', to=settings.AUTH_USER_MODEL, verbose_name='最後編輯人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='創建時間', verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改時間', verbose_name='修改時間')),
                ('is_deleted', models.BooleanField(default=False, help_text='刪除標記', verbose_name='刪除標記')),
                ('name', models.CharField(max_length=50, verbose_name='操作')),
                ('timer', models.IntegerField(default=0, help_text='單位秒。處於源狀態X秒後如果狀態都沒有過變化則自動流轉到目標狀態。設置時間有效', verbose_name='定時器(單位秒)')),
                ('condition_expression', models.JSONField(default=list, help_text='流轉條件表達式，根據表達式中的條件來確定流轉的下個狀態，格式為[{"expression":"{days} > 3 and {days}<10", "target_state":11}] 其中{}用於填充工單的欄位key,運算時會換算成實際的值，當符合條件下個狀態將變為target_state_id中的值,表達式只支持簡單的運算或datetime/time運算.loonflow會以首次匹配成功的條件為準，所以多個條件不要有沖突', max_length=1000, verbose_name='條件表達式')),
                ('attribute_type', models.IntegerField(choices=[(1, '同意'), (2, '拒絕'), (3, '其他')], default=1, help_text='屬性類型，1.同意，2.拒絕，3.其他', verbose_name='屬性類型')),
                ('field_require_check', models.BooleanField(default=True, help_text='默認在用戶點擊操作的時候需要校驗工單表單的必填項,如果設置為否則不檢查。用於如"退回"屬性的操作，不需要填寫表單內容', verbose_name='是否校驗必填項')),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transition_create_by', to=settings.AUTH_USER_MODEL, verbose_name='創建人')),
                ('destination_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dstate_transition', to='wf.state', verbose_name='目的狀態')),
                ('source_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sstate_transition', to='wf.state', verbose_name='源狀態')),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transition_update_by', to=settings.AUTH_USER_MODEL, verbose_name='最後編輯人')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wf.workflow', verbose_name='所屬工作流')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='創建時間', verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改時間', verbose_name='修改時間')),
                ('is_deleted', models.BooleanField(default=False, help_text='刪除標記', verbose_name='刪除標記')),
                ('suggestion', models.CharField(blank=True, default='', max_length=10000, verbose_name='處理意見')),
                ('participant_type', models.IntegerField(choices=[(0, '無處理人'), (1, '個人'), (2, '多人'), (4, '角色'), (6, '腳本'), (7, '工單的欄位'), (9, '代碼獲取')], default=0, help_text='0.無處理人,1.個人,2.多人等', verbose_name='處理人類型')),
                ('participant_str', models.CharField(blank=True, help_text='非人工處理的處理人相關信息', max_length=200, null=True, verbose_name='處理人')),
                ('ticket_data', models.JSONField(blank=True, default=dict, help_text='可以用於記錄當前表單數據，json格式', verbose_name='工單數據')),
                ('intervene_type', models.IntegerField(choices=[(0, '正常處理'), (1, '轉交'), (2, '加簽'), (3, '加簽處理完成'), (4, '接單'), (5, '評論'), (6, '刪除'), (7, '強制關閉'), (8, '強制修改狀態'), (9, 'hook操作'), (10, '撤回'), (11, '抄送')], default=0, help_text='流轉類型', verbose_name='乾預類型')),
                ('participant_cc', models.JSONField(blank=True, default=list, help_text='抄送給(userid列表)', verbose_name='抄送給')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticketflow_participant', to=settings.AUTH_USER_MODEL, verbose_name='處理人')),
                ('state', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='wf.state', verbose_name='當前狀態')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketflow_ticket', to='wf.ticket', verbose_name='關聯工單')),
                ('transition', models.ForeignKey(blank=True, help_text='與worklow.Transition關聯， 為空時表示認為乾預的操作', null=True, on_delete=django.db.models.deletion.CASCADE, to='wf.transition', verbose_name='流轉id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wf.workflow', verbose_name='關聯工作流'),
        ),
        migrations.AddField(
            model_name='state',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wf.workflow', verbose_name='所屬工作流'),
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='創建時間', verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改時間', verbose_name='修改時間')),
                ('is_deleted', models.BooleanField(default=False, help_text='刪除標記', verbose_name='刪除標記')),
                ('field_type', models.CharField(choices=[('string', '字元串'), ('int', '整型'), ('float', '浮點'), ('boolean', '布爾'), ('date', '日期'), ('datetime', '日期時間'), ('radio', '單選'), ('checkbox', '多選'), ('select', '單選下拉'), ('selects', '多選下拉'), ('cascader', '單選級聯'), ('cascaders', '多選級聯'), ('select_dg', '彈框單選'), ('select_dgs', '彈框多選'), ('textarea', '文本域'), ('file', '附件')], help_text='string, int, float, date, datetime, radio, checkbox, select, selects, cascader, cascaders, select_dg, select_dgs,textarea, file', max_length=50, verbose_name='類型')),
                ('field_key', models.CharField(help_text='欄位類型請盡量特殊，避免與系統中關鍵字沖突', max_length=50, verbose_name='欄位標識')),
                ('field_name', models.CharField(max_length=50, verbose_name='欄位名稱')),
                ('sort', models.IntegerField(default=0, help_text='工單基礎欄位在表單中排序為:流水號0,標題20,狀態id40,狀態名41,創建人80,創建時間100,更新時間120.前端展示工單信息的表單可以根據這個id順序排列', verbose_name='排序')),
                ('default_value', models.CharField(blank=True, help_text='前端展示時，可以將此內容作為表單中的該欄位的默認值', max_length=100, null=True, verbose_name='默認值')),
                ('description', models.CharField(blank=True, help_text='欄位的描述信息，可用於顯示在欄位的下方對該欄位的詳細描述', max_length=100, null=True, verbose_name='描述')),
                ('placeholder', models.CharField(blank=True, help_text='用戶工單詳情表單中作為欄位的占位符顯示', max_length=100, null=True, verbose_name='占位符')),
                ('field_template', models.TextField(blank=True, help_text='文本域類型欄位前端顯示時可以將此內容作為欄位的placeholder', null=True, verbose_name='文本域模板')),
                ('boolean_field_display', models.JSONField(blank=True, default=dict, help_text='當為布爾類型時候，可以支持自定義顯示形式。{"1":"是","0":"否"}或{"1":"需要","0":"不需要"}，注意數字也需要引號', verbose_name='布爾類型顯示名')),
                ('field_choice', models.JSONField(blank=True, default=list, help_text='選項值，格式為list, 例["id":1, "name":"張三"]', verbose_name='選項值')),
                ('label', models.CharField(default='', help_text='處理特殊邏輯使用,比如sys_user用於獲取用戶作為選項', max_length=1000, verbose_name='標簽')),
                ('is_hidden', models.BooleanField(default=False, help_text='可用於攜帶不需要用戶查看的欄位信息', verbose_name='是否隱藏')),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customfield_create_by', to=settings.AUTH_USER_MODEL, verbose_name='創建人')),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customfield_update_by', to=settings.AUTH_USER_MODEL, verbose_name='最後編輯人')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wf.workflow', verbose_name='所屬工作流')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
